config/routes.rb
Lydrew::Application.routes.draw do
	get "static_pages/home"

	root :to => 'static_pages#home'

	match '/about', to: 'static_pages#about'
	match '/blog', to: 'posts#index', as: :blog
	match '/blog/:id', to: 'posts#show', as: :blog_single_post
	match '/blog/archive/:month/:year', to: 'posts#show_month', as: :blog_show_month
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :content, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all.sort! { |a,b| b[:created_at] <=> a[:created_at] }
		@months ||= []
		@posts.each do |post|
			@months << [post.created_at.month, post.created_at.year]
		end
		@months = @months.uniq

	end

	def show
		@post = Post.find_by_id(params[:id])
	end

	def show_month
		@posts_temp = Post.all.sort! { |a,b| b[:created_at] <=> a[:created_at] }
		@months ||= []
		@posts_temp.each do |post|
			@months << [post.created_at.month, post.created_at.year]
		end
		@months = @months.uniq

		@posts ||= []
		Post.all.each do |post|
			if params[:year].to_i == post.created_at.year && params[:month].to_i == post.created_at.month
				@posts << post
			end
		end
		render 'index'
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<p>© 2013 Edward Lu</p>
</div>

app/views/layouts/_header.html.erb
<div id="header">
	<h1><%= image_tag("logo3.png") %></h1>
	<div id="header_nav">
		<ul id="nav_list">
			<li><%= link_to "Home", root_path, id: "home" %></li>
			<font color="white" class="spacer">|</font>
			<li><%= link_to "Blog", blog_path, id: "blog" %></li>
			<font color="white" class="spacer">|</font>
			<li><%= link_to "About", about_path, id: "about" %></li>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Enspirous</title>
	<%= favicon_link_tag 'favicon2.png' %>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
	<%= render 'layouts/header' %>
</head>
<body>

<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/posts/index.html.erb
<div id="wrapper_blog">
	<div id="content_standard">
		<div id="sidebar">
			<h3><u>Archives</u></h3>
			<% @months.each do |month| %>
				<li><%= link_to "#{Date::MONTHNAMES[month[0]]} #{month[1]}", blog_show_month_path(month: month[0], year: month[1]), id: "archive_link" %></li>
			<% end %>
		</div>
		<div id="content_holder">
			<% @posts.each do |post| %>
				<h3><%= post.title %></h3>
				<h4><%= post.created_at.to_date %></h4>
				<p class="spacing4"><%= raw post.description%></p>
				<p class="spacing4"><%= link_to "More->", blog_single_post_path(id: post.id) %></p>
				<% if post.description != @posts.last.description %>
					<div class="divider"></div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div id="wrapper_blog">
	<div id="content_standard">
		<div id="content_holder_single">
				<h3><%= @post.title %></h3>
				<h4><%= @post.created_at.to_date %></h4>
				<p class="spacing4"><%= raw @post.content%></p>
				<p class="spacing4"><%= link_to "<-Back", :back %></p>
		</div>
	</div>
</div>

app/views/static_pages/about.html.erb
<div id="wrapper_about">
	<div id="content_standard">
		<p class="spacing3">
			Hey there! I'm Edward. I love design and coding, and web design provides an awesome medium for doing both. 
		</p>
		<p class="spacing3">
			You can contact me by e-mail at eddywerdy@gmail.com, or follow me on twitter at @eddywerdy.
		</p>
	</div>
</div>

app/views/static_pages/home.html.erb
<script src="jquery.color.js"></script>

<div id="wrapper">
	<div id="banner">
		<p class="spacing1">
			Great things start with an <strong>IDEA</strong>, followed up by <strong>ACTION</strong>.
		</p>
		<div id="banner_line">
			<h2>Dev and design for all your ideas.</h2>
		</div>
	</div>
	<div id="content">
		<div id="column_left">
			<div class="circle"><%= image_tag("lightbulb.png") %></div>
			<h5>The Idea</h5>
			<p class="spacing2">This is where it all begins. It's the foundation for everything that follows. Sometimes, it springs out of nowhere, others, it's the result of inspiration from others' work. One should never underestimate the power of an idea.</p>
		</div>
		<div id="column_middle">
			<div class="circle"><%= image_tag("pencil.png") %></div>
			<h5>The Process</h5>
			<p class="spacing2">This is the action, driven by the fuel of the idea. It's where technical skill and finesse come together to produce something outstanding. Not all ideas lead to a seamless process, but sometimes, they're the most rewarding.</p>
		</div>
		<div id="column_right">
			<div class="circle"><%= image_tag("computer.png") %></div>
			<h5>The Result</h5>
			<p class="spacing2">This is the result of the work that goes into the process. An idea, framed beautifully in an appropriate medium. It's something everyone involved should be proud of, as individual as the people who produced it.</p>
		</div>
	</div>
</div>